- name: Provision App Servers
  ec2:
        key_name: "{{ keypair }}"
        group_id: "{{ security_group.group_id }}"
        instance_type: "{{ instance_type }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        image: "{{ image }}"
        wait: true
        count: "{{ number }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet_id }}"
  register: ec2

- name: Add all instance private IPs to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: ec2hosts
  with_items: "{{ec2.instances}}"

  #- debug: var=ec2
  #- debug: var=item
  #with_items: "{{ec2.instances}}"

- name: Wait for instances to listen on port:22
  wait_for:
    state: started
    host: "{{ item.public_ip }}"
    port: 22
    delay: 60
    timeout: 320
  with_items: "{{ec2.instances}}"
